learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


#template tagging
app_name = 'basic_app'

urlpatterns = [
    url('relative/', views.relative, name = 'relative'),
    url('other/', views.other, name = 'other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Terra Corp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            </li>
          </ul>
    </div>
    </div>
  </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited in you extend! -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Welcome to index</h1>
    <h1>This is index.html showing</h1>
    <a href="{% url 'basic_app:relative' %}">Link to relative url templates</a>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritence</h2>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative URL templates</title>
  </head>
  <body>
    <h1>Welcome to relative URL templates</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a>
    <p></p>
    <a href="{% url 'admin:index' %}">Admin index</a>
    <p></p>
    <a href="{% url 'index' %}">link to index</a>
  </body>
</html>